import numpy as np
import pandas as pd
from . import sql_queries as q
from .utils import fetch_data_from_bq
import json
from pathlib import Path
from typing import Optional, Dict, Any
from datetime import datetime


###################################################################################################################
#### Cohort Analysis and Retention Rates
###################################################################################################################

### Cohort Cohort Analysis Data to JSON Format

def create_cohort_report(df, path= None):
    """
    Converts a pre-calculated Cohort Analysis DataFrame into a comprehensive
    printed report and a structured JSON file.

    Parameters:
    df : Cohort analysis dataframe with pre-calculated cohort data.
    path : If provided, saves JSON output to this file path. If None, only returns dict.
    """

    # Separate DataFrames for Matrix and Averages
 
    matrix_df = df[df['is_weighted_average'] == False].copy()
    avg_df = df[df['is_weighted_average'] == True].copy()
    avg_df['retention_rate'] = (avg_df['retention_rate'] * 100).round(2) # retention rate converted to percentage

    # --- Define JSON Descriptions ---
    # Define these early so we can print them in the report header
    OVERALL_REPORT_DESCRIPTION = "Customer Cohort Analysis: retention rates (%) and total spending. Each cohort represents customers who made their first purchase in a specific month."
    AVERAGE_BY_PERIOD_INDEX_DESCRIPTION = (
        "Cross-cohort aggregations by period index. The 'period_index' represents months elapsed since that cohort's start. "
        "This metric summarizes the overall health and retention of the entire customer base based on their age (e.g., all 3-month-old customers). "
        "Retention rates are expressed in percentages."
    )
    
    print("="*80)
    print("                      *** Customer Cohort Analysis Report ***")
    print("Note that Retention rates are in percentage and total spending are in USD.")
    print("="*80)

    # Overall Summary 
    print("\n### Overall Summary ###")
    # Total distinct cohorts created during the analysis period.
    total_cohorts = matrix_df['cohort_period'].nunique()
    # Total unique customers who made a first purchase (initial cohort size).
    total_customers = int(matrix_df.groupby('cohort_period')['customers_in_cohort'].max().sum())
    # Total revenue generated by all orders within the scope of this cohort analysis.
    total_revenue = float(matrix_df['total_spent'].sum())

    analysis_start = pd.to_datetime(matrix_df['cohort_period'].min()).strftime('%Y-%m')
    analysis_end = pd.to_datetime(matrix_df['order_period'].max()).strftime('%Y-%m')

    print(f"Total Cohorts: {total_cohorts}")
    print(f"Total Customers: {total_customers:,}")
    print(f"Total Revenue: ${total_revenue:,.2f}")
    print(f"Analysis Period: {analysis_start} to {analysis_end}")
    print("-" * 80)

    # Build overall summary JSON block
    overall_summary = {
        "total_cohorts": total_cohorts,
        "total_customers": total_customers,
        "total_revenue": round(total_revenue, 2),
        "analysis_period_start": analysis_start,
        "analysis_period_end": analysis_end
    }

    # Cross-Cohort Aggregations (by Period Index) 
    print("\n### Cross-Cohort Aggregation Results (by Period Index) ###")
    print("Cross-cohort aggregations by period index (months elapsed since that cohort's start).")
    print("-" * 80)

    # Select pre-calculated data from the aggregated DataFrame
    avg_display = avg_df[['period_index', 'active_customers', 'retention_rate', 'total_spent']].copy()
    avg_display_table = avg_display.copy()
    avg_display_table.columns = ['Period Index', 'Active Customers (Total)', 'Retention % (Cross-Cohort)',
                                 'Total Spent (Aggregated)']

    avg_display_table['Retention % (Cross-Cohort)'] = avg_display_table['Retention % (Cross-Cohort)'].apply(
        lambda x: f"{x}%" if pd.notna(x) else "N/A"
    )
    avg_display_table['Total Spent (Aggregated)'] = avg_display_table['Total Spent (Aggregated)'].apply(
        lambda x: f"${x:,.2f}" if pd.notna(x) else "N/A"
    )

    print(avg_display_table.to_string(index=False))
    print("-" * 80)

    # Build JSON block for cross-cohort aggregations
    aggregated_by_index_month = []
    for _, row in avg_df.iterrows():
        aggregated_by_index_month.append({
            "period_index": int(row['period_index']) if pd.notna(row['period_index']) else None,
            "retention_rate": round(row['retention_rate'], 2) if pd.notna(row['retention_rate']) else None,
            "total_spent": round(row['total_spent'], 2) if pd.notna(row['total_spent']) else None,
            "total_active_customers": int(row['active_customers']) if pd.notna(row['active_customers']) else None
        })

    # Final Output Construction 
    output = {
        "description": OVERALL_REPORT_DESCRIPTION,
        "overall_summary": overall_summary,
        "average_by_period_index": {
            "description": AVERAGE_BY_PERIOD_INDEX_DESCRIPTION,
            "data": aggregated_by_index_month}
    }
    # Save and Return 
    if path:
        path_obj = Path(path)
        path_obj.parent.mkdir(parents=True, exist_ok=True)
        with open(path_obj, 'w') as f:
            json.dump(output, f, indent=2, default=str)
        print(f"\n Cohort analysis saved to: {path}")

    return output

# Performing analysis and generating reports

directory = Path(__file__).resolve().parents[2] / "python" / "output" / "Analysis" 

# Cohort Customer Retention Data
df1 = fetch_data_from_bq(q.GET_BI_CUSTOMER_COHORTS)
create_cohort_report(df=df1, path= directory / "cohort_analysis_report.json")


###################################################################################################################
#### RFM Analysis and Customer Segmentation
###################################################################################################################

### RFM Analysis Data to JSON Format

def create_rfm_report(df: pd.DataFrame, path: Optional[str] = None, further_notes="") -> Dict[str, Any]:
    """
    Convert RFM analysis DataFrame to JSON format with printed report. Additional notes can be provided.
    Parameters:
    -----------
    df : RFM dataframe with columns: customer_unique_id, total_orders, total_spent,
        recency_days, r_score, f_score, m_score, rfm_score, rfm_label, rfm_segment
    path : If provided, saves JSON to this path.
    Returns: Structured JSON-ready dictionary
    """
    
    # Convert data types
    int_columns = ['total_orders', 'recency_days', 'r_score', 'f_score', 'm_score',
                   'rfm_score', 'rfm_label']
    df[int_columns] = df[int_columns].astype(int)
    df['total_spent'] = df['total_spent'].astype(float)
    
    print("="*80)
    print("              *** RFM (Recency, Frequency, Monetary) Analysis Report ***")
    print("="*80)
    
    # --- Summary Statistics ---
    print("\n### Overall Summary ###")
    total_customers = len(df)
    total_revenue = float(df['total_spent'].sum())
    avg_customer_value = float(df['total_spent'].mean())
    avg_orders_per_customer = float(df['total_orders'].mean())
    avg_recency_days = float(df['recency_days'].mean())
    
    print(f"Total Customers: {total_customers:,}")
    print(f"Total Revenue: ${total_revenue:,.2f}")
    print(f"Average Customer Value: ${avg_customer_value:,.2f}")
    print(f"Average Orders per Customer: {avg_orders_per_customer:.2f}")
    print(f"Average Recency (Days): {avg_recency_days:.2f}")
    print("-" * 80)
    
    # --- RFM Score Distribution ---
    print("\n### RFM Score Distribution ###")
    r_avg = float(df['r_score'].mean())
    r_median = int(df['r_score'].median())
    f_avg = float(df['f_score'].mean())
    f_median = int(df['f_score'].median())
    m_avg = float(df['m_score'].mean())
    m_median = int(df['m_score'].median())
    
    rfm_stats = pd.DataFrame({
        'Score Type': ['Recency', 'Frequency', 'Monetary'],
        'Avg Score': [round(r_avg, 2), round(f_avg, 2), round(m_avg, 2)],
        'Median Score': [r_median, f_median, m_median],
        'Metric Avg': [
            f"{avg_recency_days:.2f} days",
            f"{avg_orders_per_customer:.2f} orders",
            f"${avg_customer_value:,.2f}"
        ]
    })
    print(rfm_stats.to_string(index=False))
    print("-" * 80)
    
    # --- Segment Distribution ---
    print("\n### Customer Segment Distribution ###")
    segment_dist = df.groupby('rfm_segment').agg({
        'customer_unique_id': 'count',
        'total_spent': 'sum',
        'total_orders': 'sum'
    }).reset_index()
    
    segment_dist['percentage'] = (segment_dist['customer_unique_id'] / total_customers * 100).round(2)
    segment_dist['revenue_percentage'] = (segment_dist['total_spent'] / total_revenue * 100).round(2)
    segment_dist = segment_dist.sort_values('total_spent', ascending=False)
    
    segment_display = segment_dist.copy()
    segment_display.columns = ['Segment', 'Customers', 'Total Revenue', 'Total Orders', 
                                'Customer %', 'Revenue %']
    segment_display['Total Revenue'] = segment_display['Total Revenue'].apply(lambda x: f"${x:,.2f}")
    segment_display['Customer %'] = segment_display['Customer %'].apply(lambda x: f"{x}%")
    segment_display['Revenue %'] = segment_display['Revenue %'].apply(lambda x: f"{x}%")
    
    print(segment_display.to_string(index=False))
    print("-" * 80)
    
    # --- Detailed Segment Metrics ---
    print("\n### Detailed Segment Metrics ###")
    segment_metrics = df.groupby('rfm_segment').agg({
        'total_orders': ['mean', 'median'],
        'total_spent': ['mean', 'median'],
        'recency_days': ['mean', 'median'],
        'r_score': 'mean',
        'f_score': 'mean',
        'm_score': 'mean'
    }).reset_index()
    
    segment_metrics.columns = ['segment', 'avg_orders', 'median_orders', 'avg_spent', 
                                'median_spent', 'avg_recency', 'median_recency',
                                'avg_r_score', 'avg_f_score', 'avg_m_score']
    
    segment_metrics_display = segment_metrics.copy()
    segment_metrics_display['avg_spent'] = segment_metrics_display['avg_spent'].apply(lambda x: f"${x:,.2f}")
    segment_metrics_display['median_spent'] = segment_metrics_display['median_spent'].apply(lambda x: f"${x:,.2f}")
    segment_metrics_display = segment_metrics_display[['segment', 'avg_orders', 'avg_spent', 
                                                         'avg_recency', 'avg_r_score', 
                                                         'avg_f_score', 'avg_m_score']]
    segment_metrics_display.columns = ['Segment', 'Avg Orders', 'Avg Spent', 'Avg Recency', 
                                        'Avg R', 'Avg F', 'Avg M']
    
    print(segment_metrics_display.round(2).to_string(index=False))
    print("-" * 80)
    
    # --- Top Segments ---
    print("\n### Top 5 Segments by Revenue ###")
    top_revenue = segment_dist.nlargest(5, 'total_spent')[['rfm_segment', 'total_spent', 'revenue_percentage']]
    top_revenue_display = top_revenue.copy()
    top_revenue_display['total_spent'] = top_revenue_display['total_spent'].apply(lambda x: f"${x:,.2f}")
    top_revenue_display['revenue_percentage'] = top_revenue_display['revenue_percentage'].apply(lambda x: f"{x}%")
    top_revenue_display.columns = ['Segment', 'Total Revenue', 'Revenue %']
    print(top_revenue_display.to_string(index=False))
    
    print("\n### Top 5 Segments by Customer Count ###")
    top_count = segment_dist.nlargest(5, 'customer_unique_id')[['rfm_segment', 'customer_unique_id', 'percentage']]
    top_count_display = top_count.copy()
    top_count_display['percentage'] = top_count_display['percentage'].apply(lambda x: f"{x}%")
    top_count_display.columns = ['Segment', 'Customer Count', 'Customer %']
    print(top_count_display.to_string(index=False))
    print(f"\n* Note that:\n {further_notes}")
    print("\n" + "="*80)
    
    # --- Build JSON Output ---
    output = {
        "description": "RFM (Recency, Frequency, Monetary) customer segmentation analysis",
    
        "summary": {
            "total_customers": int(total_customers),
            "total_revenue": round(total_revenue, 2),
            "avg_customer_value": round(avg_customer_value, 2),
            "avg_orders_per_customer": round(avg_orders_per_customer, 2),
            "avg_recency_days": round(avg_recency_days, 2)
        },
        
        "rfm_segment_distribution": {
            "description": "Customer count and value distribution across RFM segments",
            "data": []
        },
        
        "segment_metrics": {
            "description": "Detailed metrics for each customer segment",
            "data": []
        },
        
        "rfm_score_distribution": {
            "description": "Statistical distribution of R, F, and M scores",
            "recency": {
                "avg_score": round(r_avg, 2),
                "median_score": r_median,
                "avg_days": round(avg_recency_days, 2)
            },
            "frequency": {
                "avg_score": round(f_avg, 2),
                "median_score": f_median,
                "avg_orders": round(avg_orders_per_customer, 2)
            },
            "monetary": {
                "avg_score": round(m_avg, 2),
                "median_score": m_median,
                "avg_spent": round(avg_customer_value, 2)
            }
        },
        "Additional Note About Data": further_notes
    }
    
    # Populate segment distribution data (already sorted by revenue in descending order)
    for _, row in segment_dist.iterrows():
        output['rfm_segment_distribution']['data'].append({
            "segment": str(row['rfm_segment']),
            "customer_count": int(row['customer_unique_id']),
            "percentage_of_customers": float(row['percentage']),
            "total_revenue": round(float(row['total_spent']), 2),
            "percentage_of_revenue": float(row['revenue_percentage']),
            "total_orders": int(row['total_orders'])
        })
    
    # Populate segment metrics data
    for _, row in segment_metrics.iterrows():
        output['segment_metrics']['data'].append({
            "segment": str(row['segment']),
            "avg_orders": round(float(row['avg_orders']), 2),
            "median_orders": int(row['median_orders']),
            "avg_spent": round(float(row['avg_spent']), 2),
            "median_spent": round(float(row['median_spent']), 2),
            "avg_recency_days": round(float(row['avg_recency']), 2),
            "median_recency_days": int(row['median_recency']),
            "avg_rfm_scores": {
                "recency": round(float(row['avg_r_score']), 2),
                "frequency": round(float(row['avg_f_score']), 2),
                "monetary": round(float(row['avg_m_score']), 2)
            }
        })

    # Save to file if path is provided
    if path:
        path_obj = Path(path)
        path_obj.parent.mkdir(parents=True, exist_ok=True)
        with open(path_obj, 'w') as f:
            json.dump(output, f, indent=2, default=str)
        print(f"\nRFM analysis saved to: {path}")
    return output


# RFM Analysis Data 
df2 = fetch_data_from_bq(q.GET_BI_CUSTOMER_RFM)
create_rfm_report(df=df2, path= directory / "rfm_analysis_report.json", 
                  further_notes="The majority of customers (i.e. more than 95 percent of customers) only had only 1 order so the histogram of F (Frequency) is highly skewed")


###################################################################################################################
#### Products Performance  
###################################################################################################################

### Product Performance Data to JSON Format

def create_product_performance_report(df: pd.DataFrame, path: Optional[str] = None) -> Dict[str, Any]:
    """    
    Parameters:
    -----------
    df : Product performance dataframe with columns:
        - product_id, product_category_name, total_orders, total_items_sold,
          total_revenue, avg_review_score, avg_delivery_days
    path : If provided, saves JSON to this path.
    
    Returns:
    --------
    Dict[str, Any]
        Structured JSON-ready dictionary
    """
    
    print("="*100)
    print("                  *** Product Performance Analysis Report ***")
    print("="*100)
    
    int_cols = ['total_orders', 'total_items_sold']
    flt_cols = ['total_revenue', 'avg_review_score', 'avg_delivery_days']
    df[int_cols] = df[int_cols].astype(int)
    df[flt_cols] = df[flt_cols].astype(float)
    # --- Overall Summary ---
    print("\n### Overall Summary ###")
    total_products = len(df)
    total_revenue = float(df['total_revenue'].sum())
    total_items_sold = int(df['total_items_sold'].sum())
    total_orders = int(df['total_orders'].sum())
    avg_review_score = float(df['avg_review_score'].mean())
    avg_delivery_days = float(df['avg_delivery_days'].mean())
    
    print(f"Total Products: {total_products:,}")
    print(f"Total Revenue: ${total_revenue:,.2f}")
    print(f"Total Items Sold: {total_items_sold:,}")
    print(f"Total Orders: {total_orders:,}")
    print(f"Average Review Score: {avg_review_score:.2f}")
    print(f"Average Delivery Days: {avg_delivery_days:.2f}")
    print("-" * 100)
    
    # --- Top 10 Products by Items Sold (High Demand) ---
    print("\n### Top 10 Products by Items Sold (High Demand) ###")
    top_by_items = df.nlargest(10, 'total_items_sold').copy()
    
    top_items_display = top_by_items[['product_id', 'product_category_name', 'total_items_sold', 
                                       'total_orders', 'total_revenue', 'avg_review_score', 
                                       'avg_delivery_days']].copy()
    top_items_display['product_id'] = top_items_display['product_id'].str[:16] + '...'
    top_items_display['total_revenue'] = top_items_display['total_revenue'].apply(lambda x: f"${x:,.2f}")
    top_items_display.columns = ['Product ID', 'Category', 'Items Sold', 'Orders', 
                                  'Revenue', 'Avg Review', 'Avg Delivery']
    
    print(top_items_display.to_string(index=False))
    print("-" * 100)
    
    # --- Top 10 Products by Revenue ---
    print("\n### Top 10 Products by Revenue (Highest Revenue) ###")
    top_by_revenue = df.nlargest(10, 'total_revenue').copy()
    
    top_revenue_display = top_by_revenue[['product_id', 'product_category_name', 'total_revenue',
                                           'total_items_sold', 'total_orders', 'avg_review_score', 
                                           'avg_delivery_days']].copy()
    top_revenue_display['product_id'] = top_revenue_display['product_id'].str[:16] + '...'
    top_revenue_display['total_revenue'] = top_revenue_display['total_revenue'].apply(lambda x: f"${x:,.2f}")
    top_revenue_display.columns = ['Product ID', 'Category', 'Revenue', 'Items Sold', 
                                    'Orders', 'Avg Review', 'Avg Delivery']
    
    print(top_revenue_display.to_string(index=False))
    print("-" * 100)
    
    # --- Bottom 10 Products (Worst Selling) ---
    print("\n### Bottom 10 Products by Items Sold (Worst Selling) ###")
    bottom_by_items = df.nsmallest(10, 'total_items_sold').copy()
    
    bottom_items_display = bottom_by_items[['product_id', 'product_category_name', 'total_items_sold',
                                             'total_orders', 'total_revenue', 'avg_review_score', 
                                             'avg_delivery_days']].copy()
    bottom_items_display['product_id'] = bottom_items_display['product_id'].str[:16] + '...'
    bottom_items_display['total_revenue'] = bottom_items_display['total_revenue'].apply(lambda x: f"${x:,.2f}")
    bottom_items_display.columns = ['Product ID', 'Category', 'Items Sold', 'Orders', 
                                     'Revenue', 'Avg Review', 'Avg Delivery']
    
    print(bottom_items_display.to_string(index=False))
    print("-" * 100)
    
    # --- Correlation Analysis ---
    print("\n### Correlation Analysis ###")
    print("Examining relationships between Items Sold, Review Score, and Delivery Days")
    print()
    
    correlation_cols = ['total_items_sold', 'avg_review_score', 'avg_delivery_days']
    corr_matrix = df[correlation_cols].corr(method='spearman')
    
    print("Correlation Matrix:")
    corr_display = corr_matrix.copy()
    corr_display.columns = ['Items Sold', 'Review Score', 'Delivery Days']
    corr_display.index = ['Items Sold', 'Review Score', 'Delivery Days']
    print(corr_display.round(3).to_string())
    print()
    
    # Interpret correlations
    items_review_corr = corr_matrix.loc['total_items_sold', 'avg_review_score']
    items_delivery_corr = corr_matrix.loc['total_items_sold', 'avg_delivery_days']
    review_delivery_corr = corr_matrix.loc['avg_review_score', 'avg_delivery_days']
        
    print("\n" + "="*100)
    
    # --- Build JSON Output ---
    output = {
        "description": "Product performance analysis including top/bottom performers and correlation insights",
        
        "summary": {
            "total_products": int(total_products),
            "total_revenue": round(total_revenue, 2),
            "total_items_sold": int(total_items_sold),
            "total_orders": int(total_orders),
            "avg_review_score": round(avg_review_score, 2),
            "avg_delivery_days": round(avg_delivery_days, 2)
        },
        
        "top_performers": {
            "by_items_sold": {
                "description": "Top 10 products by items sold (high demand)",
                "data": []
            },
            "by_revenue": {
                "description": "Top 10 products by total revenue",
                "data": []
            }
        },
        
        "bottom_performers": {
            "description": "Bottom 10 products by items sold (worst selling)",
            "data": []
        },
        
        "correlation_analysis": {
            "description": "Correlation between items sold, review score, and delivery days",
            "correlation_matrix": {
                "items_sold_vs_review_score": round(float(items_review_corr), 3),
                "items_sold_vs_delivery_days": round(float(items_delivery_corr), 3),
                "review_score_vs_delivery_days": round(float(review_delivery_corr), 3)
            },
            "full_matrix": corr_matrix.round(3).to_dict()
        }
    }
    
    # Populate top performers by items sold
    for _, row in top_by_items.iterrows():
        output['top_performers']['by_items_sold']['data'].append({
            "product_id": str(row['product_id']),
            "product_category_name": str(row['product_category_name']),
            "total_items_sold": int(row['total_items_sold']),
            "total_orders": int(row['total_orders']),
            "total_revenue": round(float(row['total_revenue']), 2),
            "avg_review_score": round(float(row['avg_review_score']), 2),
            "avg_delivery_days": round(float(row['avg_delivery_days']), 2)
        })
    
    # Populate top performers by revenue
    for _, row in top_by_revenue.iterrows():
        output['top_performers']['by_revenue']['data'].append({
            "product_id": str(row['product_id']),
            "product_category_name": str(row['product_category_name']),
            "total_revenue": round(float(row['total_revenue']), 2),
            "total_items_sold": int(row['total_items_sold']),
            "total_orders": int(row['total_orders']),
            "avg_review_score": round(float(row['avg_review_score']), 2),
            "avg_delivery_days": round(float(row['avg_delivery_days']), 2)
        })
    
    # Populate bottom performers
    for _, row in bottom_by_items.iterrows():
        output['bottom_performers']['data'].append({
            "product_id": str(row['product_id']),
            "product_category_name": str(row['product_category_name']),
            "total_items_sold": int(row['total_items_sold']),
            "total_orders": int(row['total_orders']),
            "total_revenue": round(float(row['total_revenue']), 2),
            "avg_review_score": round(float(row['avg_review_score']), 2),
            "avg_delivery_days": round(float(row['avg_delivery_days']), 2)
        })
    
    # Save to file if path is provided
    if path:
        path_obj = Path(path)
        path_obj.parent.mkdir(parents=True, exist_ok=True)
        
        with open(path_obj, 'w') as f:
            json.dump(output, f, indent=2, default=str)
        
        print(f"\nProduct performance analysis saved to: {path}")
    
    return output

# Product Performance Data 
df3 = fetch_data_from_bq(q.GET_BI_PRODUCT_PERFORMANCE)
create_product_performance_report(df=df3, path= directory / "product_performance_report.json")

###################################################################################################################
#### Product Category Performance  
###################################################################################################################

def create_category_performance_report(df: pd.DataFrame, path: Optional[str] = None) -> Dict[str, Any]:
    """
    Analyze product category performance and create a comprehensive report.
    Parameters:
    -----------
    df : Product category performance dataframe with columns:
        - product_category_name, total_items_sold, total_revenue
    path : If provided, saves JSON to this path.
    """
    
    print("="*80)
    print("              *** Product Category Performance Analysis Report ***")
    print("="*80)

    df['total_items_sold'] = df['total_items_sold'].fillna(0).astype(int)
    df['total_revenue'] = df['total_revenue'].fillna(0.0).astype(float)

    # --- Overall Summary ---
    print("\n### Overall Summary ###")
    total_categories = len(df)
    total_revenue = float(df['total_revenue'].sum())
    total_items_sold = int(df['total_items_sold'].sum())
    print(f"Total Categories: {total_categories:,}")
    print(f"Total Revenue: ${total_revenue:,.2f}")
    print(f"Total Items Sold: {total_items_sold:,}")
    print("-" * 80)
    
    # --- Top 10 Categories by Items Sold (High Demand) ---
    print("\n### Top 10 Categories by Items Sold (High Demand) ###")
    top_by_items = df.nlargest(10, 'total_items_sold').copy()
    
    # Calculate percentage of total
    top_by_items['items_percentage'] = (top_by_items['total_items_sold'] / total_items_sold * 100).round(2)
    top_by_items['revenue_percentage'] = (top_by_items['total_revenue'] / total_revenue * 100).round(2)
    
    top_items_display = top_by_items[['product_category_name', 'total_items_sold', 
                                       'items_percentage', 'total_revenue', 
                                       'revenue_percentage']].copy()
    top_items_display['total_revenue'] = top_items_display['total_revenue'].apply(lambda x: f"${x:,.2f}")
    top_items_display['items_percentage'] = top_items_display['items_percentage'].apply(lambda x: f"{x}%")
    top_items_display['revenue_percentage'] = top_items_display['revenue_percentage'].apply(lambda x: f"{x}%")
    top_items_display.columns = ['Category', 'Items Sold', 'Items %', 'Revenue', 'Revenue %']
    
    print(top_items_display.to_string(index=False))
    print("-" * 80)
    
    # --- Top 10 Categories by Revenue ---
    print("\n### Top 10 Categories by Revenue (Highest Revenue) ###")
    top_by_revenue = df.nlargest(10, 'total_revenue').copy()
    
    # Calculate percentage of total
    top_by_revenue['revenue_percentage'] = (top_by_revenue['total_revenue'] / total_revenue * 100).round(2)
    top_by_revenue['items_percentage'] = (top_by_revenue['total_items_sold'] / total_items_sold * 100).round(2)
    
    top_revenue_display = top_by_revenue[['product_category_name', 'total_revenue',
                                           'revenue_percentage', 'total_items_sold', 
                                           'items_percentage']].copy()
    top_revenue_display['total_revenue'] = top_revenue_display['total_revenue'].apply(lambda x: f"${x:,.2f}")
    top_revenue_display['revenue_percentage'] = top_revenue_display['revenue_percentage'].apply(lambda x: f"{x}%")
    top_revenue_display['items_percentage'] = top_revenue_display['items_percentage'].apply(lambda x: f"{x}%")
    top_revenue_display.columns = ['Category', 'Revenue', 'Revenue %', 'Items Sold', 'Items %']
    
    print(top_revenue_display.to_string(index=False))
    print("-" * 80)
    
    # --- Bottom 10 Categories (Worst Selling) ---
    print("\n### Bottom 10 Categories by Revenue (Worst Selling) ###")
    bottom_by_items = df.nsmallest(10, 'total_revenue').copy()
    
    # Calculate percentage of total
    bottom_by_items['items_percentage'] = (bottom_by_items['total_items_sold'] / total_items_sold * 100).round(2)
    bottom_by_items['revenue_percentage'] = (bottom_by_items['total_revenue'] / total_revenue * 100).round(2)
    
    bottom_items_display = bottom_by_items[['product_category_name', 'total_items_sold',
                                             'items_percentage', 'total_revenue', 
                                             'revenue_percentage']].copy()
    bottom_items_display['total_revenue'] = bottom_items_display['total_revenue'].apply(lambda x: f"${x:,.2f}")
    bottom_items_display['items_percentage'] = bottom_items_display['items_percentage'].apply(lambda x: f"{x}%")
    bottom_items_display['revenue_percentage'] = bottom_items_display['revenue_percentage'].apply(lambda x: f"{x}%")
    bottom_items_display.columns = ['Category', 'Items Sold', 'Items %', 'Revenue', 'Revenue %']
    
    print(bottom_items_display.to_string(index=False))
    print("-" * 80)
    
    # --- Category Concentration Analysis ---
    print("\n### Category Concentration Analysis ###")
    # Calculate cumulative percentages
    df_sorted = df.sort_values('total_revenue', ascending=False).copy()
    df_sorted['cumulative_revenue_pct'] = (df_sorted['total_revenue'].cumsum() / total_revenue * 100)
    
    top_20_pct_categories = (df_sorted['cumulative_revenue_pct'] <= 80).sum()
    top_20_pct_revenue = df_sorted[df_sorted['cumulative_revenue_pct'] <= 80]['total_revenue'].sum()
    
    print(f"Top {top_20_pct_categories} categories account for 80% of revenue")
    print(f"  → Revenue concentration ratio: {top_20_pct_categories}/{total_categories} = {(top_20_pct_categories/total_categories*100):.1f}%")
    
    top_5_revenue_share = (df.nlargest(5, 'total_revenue')['total_revenue'].sum() / total_revenue * 100)
    print(f"Top 5 categories account for {top_5_revenue_share:.1f}% of total revenue")
    
    print("\n" + "="*80)
    
    # --- Build JSON Output ---
    output = {
        "description": "Product category performance analysis including top/bottom performers and concentration metrics",
        
        "summary": {
            "total_categories": int(total_categories),
            "total_revenue": round(total_revenue, 2),
            "total_items_sold": int(total_items_sold)
        },
        
        "top_performers": {
            "by_items_sold": {
                "description": "Top 10 categories by items sold (high demand)",
                "data": []
            },
            "by_revenue": {
                "description": "Top 10 categories by total revenue",
                "data": []
            }
        },
        
        "bottom_performers": {
            "description": "Bottom 10 categories by revenue (worst selling)",
            "data": []
        },
        
        "concentration_analysis": {
            "description": "Revenue concentration metrics across categories",
            "categories_for_80pct_revenue": int(top_20_pct_categories),
            "top_5_revenue_share_pct": round(float(top_5_revenue_share), 2),
            "concentration_ratio": round(float(top_20_pct_categories/total_categories*100), 2)
        }
    }
    
    # Populate top performers by items sold
    top_by_items_reset = top_by_items.reset_index(drop=True)
    for _, row in top_by_items_reset.iterrows():
        output['top_performers']['by_items_sold']['data'].append({
            "product_category_name": str(row['product_category_name']),
            "total_items_sold": int(row['total_items_sold']),
            "items_percentage": float(row['items_percentage']),
            "total_revenue": round(float(row['total_revenue']), 2),
            "revenue_percentage": float(row['revenue_percentage'])
        })
    
    # Populate top performers by revenue
    top_by_revenue_reset = top_by_revenue.reset_index(drop=True)
    for _, row in top_by_revenue_reset.iterrows():
        output['top_performers']['by_revenue']['data'].append({
            "product_category_name": str(row['product_category_name']),
            "total_revenue": round(float(row['total_revenue']), 2),
            "revenue_percentage": float(row['revenue_percentage']),
            "total_items_sold": int(row['total_items_sold']),
            "items_percentage": float(row['items_percentage'])
        })
    
    # Populate bottom performers
    bottom_by_items_reset = bottom_by_items.reset_index(drop=True)
    for _, row in bottom_by_items_reset.iterrows():
        output['bottom_performers']['data'].append({
            "product_category_name": str(row['product_category_name']),
            "total_items_sold": int(row['total_items_sold']),
            "items_percentage": float(row['items_percentage']),
            "total_revenue": round(float(row['total_revenue']), 2),
            "revenue_percentage": float(row['revenue_percentage'])
        })
    
    # Save to file if path is provided
    if path:
        path_obj = Path(path)
        path_obj.parent.mkdir(parents=True, exist_ok=True)
        with open(path_obj, 'w') as f:
            json.dump(output, f, indent=2, default=str)
        print(f"\n Category performance analysis saved to: {path}")
    return output

# Category Performance Data 
df4 = fetch_data_from_bq(q.GET_product_category_performance)
create_category_performance_report(df=df4, path= directory / "category_performance_report.json")

###################################################################################################################
#### Sellers Performance  
###################################################################################################################
def create_seller_performance_report(df, path=None):
    """
    Analyze seller performance and create a comprehensive report.
    Parameters:
    -----------
    df : Seller performance dataframe with columns:
        - seller_id, total_orders, total_items_sold, total_revenue,
          avg_delivery_days, avg_review_score
    path : If provided, saves JSON to this path.
    """
    
    print("="*80)
    print("                 *** Seller Performance Analysis Report ***")
    print("="*80)
    
    # Data type conversions
    int_cols = ['total_orders', 'total_items_sold']
    flt_cols = ['total_revenue', 'avg_delivery_days']
    df[int_cols] = df[int_cols].astype(int)
    df[flt_cols] = df[flt_cols].astype(float)
    
    # Handle review scores separately - convert only non-null values
    df['avg_review_score'] = pd.to_numeric(df['avg_review_score'], errors='coerce')
    
    # Create subset for review analysis
    df_with_reviews = df[df['avg_review_score'].notna()].copy()
    sellers_without_reviews = len(df) - len(df_with_reviews)

    # --- Overall Summary ---
    print("\n### Overall Summary ###")
    total_sellers = len(df)
    total_orders = int(df['total_orders'].sum())
    total_items = int(df['total_items_sold'].sum())
    total_revenue = float(df['total_revenue'].sum())
    avg_delivery = float(df['avg_delivery_days'].mean())
    avg_review = float(df_with_reviews['avg_review_score'].mean()) if len(df_with_reviews) > 0 else 0
    
    print(f"Total Sellers: {total_sellers:,}")
    print(f"Total Orders: {total_orders:,}")
    print(f"Total Items Sold: {total_items:,}")
    print(f"Total Revenue: ${total_revenue:,.2f}")
    print(f"Average Delivery Time: {avg_delivery:.1f} days")
    if len(df_with_reviews) > 0:
        print(f"Average Review Score: {avg_review:.2f} / 5.0 (based on {len(df_with_reviews):,} sellers)")
        if sellers_without_reviews > 0:
            print(f"  → {sellers_without_reviews:,} sellers have no reviews yet")
    else:
        print(f"No sellers have reviews yet")
    print("-" * 80)
    
    # --- Top 10 Sellers by Revenue ---
    print("\n### Top 10 Sellers by Revenue ###")
    top_by_revenue = df.nlargest(10, 'total_revenue').copy()
    
    # Calculate revenue percentage
    top_by_revenue['revenue_pct'] = (top_by_revenue['total_revenue'] / total_revenue * 100).round(2)
    
    top_revenue_display = top_by_revenue[['seller_id', 'total_revenue', 'revenue_pct', 
                                           'total_orders', 'avg_review_score', 
                                           'avg_delivery_days']].copy()
    top_revenue_display['total_revenue'] = top_revenue_display['total_revenue'].apply(lambda x: f"${x:,.2f}")
    top_revenue_display['revenue_pct'] = top_revenue_display['revenue_pct'].apply(lambda x: f"{x}%")
    top_revenue_display['avg_review_score'] = top_revenue_display['avg_review_score'].apply(
        lambda x: f"{x:.2f}" if pd.notna(x) else "N/A"
    )
    top_revenue_display['avg_delivery_days'] = top_revenue_display['avg_delivery_days'].apply(lambda x: f"{x:.1f}")
    top_revenue_display.columns = ['Seller ID', 'Revenue', 'Revenue %', 'Orders', 'Avg Review', 'Avg Delivery']
    
    print(top_revenue_display.to_string(index=False))
    print("-" * 80)
    
    # --- Top 10 Sellers by Review Score (min 10 orders) ---
    print("\n### Top 10 Sellers by Review Score (min 10 orders) ###")
    df_min_orders = df_with_reviews[df_with_reviews['total_orders'] >= 10].copy()
    
    if len(df_min_orders) > 0:
        top_by_review = df_min_orders.nlargest(10, 'avg_review_score').copy()
        
        top_review_display = top_by_review[['seller_id', 'avg_review_score', 'total_orders',
                                             'total_revenue', 'avg_delivery_days']].copy()
        top_review_display['avg_review_score'] = top_review_display['avg_review_score'].apply(lambda x: f"{x:.2f}")
        top_review_display['total_revenue'] = top_review_display['total_revenue'].apply(lambda x: f"${x:,.2f}")
        top_review_display['avg_delivery_days'] = top_review_display['avg_delivery_days'].apply(lambda x: f"{x:.1f}")
        top_review_display.columns = ['Seller ID', 'Avg Review', 'Orders', 'Revenue', 'Avg Delivery']
        
        print(top_review_display.to_string(index=False))
    else:
        print("No sellers with >= 10 orders and reviews found")
    print("-" * 80)
    
    # --- Bottom 10 Sellers by Review Score (min 10 orders) ---
    print("\n### Bottom 10 Sellers by Review Score (min 10 orders) ###")
    if len(df_min_orders) > 0:
        bottom_by_review = df_min_orders.nsmallest(10, 'avg_review_score').copy()
        
        bottom_review_display = bottom_by_review[['seller_id', 'avg_review_score', 'total_orders',
                                                   'total_revenue', 'avg_delivery_days']].copy()
        bottom_review_display['avg_review_score'] = bottom_review_display['avg_review_score'].apply(lambda x: f"{x:.2f}")
        bottom_review_display['total_revenue'] = bottom_review_display['total_revenue'].apply(lambda x: f"${x:,.2f}")
        bottom_review_display['avg_delivery_days'] = bottom_review_display['avg_delivery_days'].apply(lambda x: f"{x:.1f}")
        bottom_review_display.columns = ['Seller ID', 'Avg Review', 'Orders', 'Revenue', 'Avg Delivery']
        
        print(bottom_review_display.to_string(index=False))
    else:
        print("No sellers with >= 10 orders and reviews found")
    print("-" * 80)
    
    # --- Seller Concentration Analysis ---
    print("\n### Seller Concentration Analysis ###")
    df_sorted = df.sort_values('total_revenue', ascending=False).copy()
    df_sorted['cumulative_revenue_pct'] = (df_sorted['total_revenue'].cumsum() / total_revenue * 100)
    
    sellers_for_80pct = (df_sorted['cumulative_revenue_pct'] <= 80).sum()
    top_10_revenue_share = (df.nlargest(10, 'total_revenue')['total_revenue'].sum() / total_revenue * 100)
    
    print(f"Top {sellers_for_80pct} sellers account for 80% of revenue")
    print(f"  → Concentration ratio: {sellers_for_80pct}/{total_sellers} = {(sellers_for_80pct/total_sellers*100):.1f}%")
    print(f"Top 10 sellers account for {top_10_revenue_share:.1f}% of total revenue")
    print("-" * 80)
    
    # --- Review Score Distribution (only for sellers with reviews) ---
    if len(df_with_reviews) > 0:
        print("\n### Review Score Distribution ###")
        print(f"(Based on {len(df_with_reviews):,} sellers with reviews)")
        review_bins = [0, 2.0, 3.0, 4.0, 4.5, 5.0]
        review_labels = ['Poor (0-2)', 'Fair (2-3)', 'Good (3-4)', 'Very Good (4-4.5)', 'Excellent (4.5-5)']
        df_with_reviews['review_bracket'] = pd.cut(df_with_reviews['avg_review_score'], bins=review_bins, 
                                                     labels=review_labels, right=True, include_lowest=True)
        
        review_dist = df_with_reviews['review_bracket'].value_counts().sort_index()
        for bracket in review_labels:
            count = review_dist.get(bracket, 0)
            pct = (count / len(df_with_reviews) * 100) if len(df_with_reviews) > 0 else 0
            print(f"{bracket:22s}: {count:5,} sellers ({pct:5.1f}%)")
        print("-" * 80)
    else:
        print("\n### Review Score Distribution ###")
        print("No review data available")
        print("-" * 80)
    
    print("\n" + "="*80)
    
    # --- Build JSON Output ---
    output = {
        "description": "Seller performance analysis including revenue, reviews, and delivery metrics",
        
        "summary": {
            "total_sellers": int(total_sellers),
            "sellers_with_reviews": int(len(df_with_reviews)),
            "sellers_without_reviews": int(sellers_without_reviews),
            "total_orders": int(total_orders),
            "total_items_sold": int(total_items),
            "total_revenue": round(float(total_revenue), 2),
            "avg_delivery_days": round(float(avg_delivery), 1),
            "avg_review_score": round(float(avg_review), 2) if len(df_with_reviews) > 0 else None
        },
        
        "top_performers": {
            "by_revenue": {
                "description": "Top 10 sellers by total revenue",
                "data": []
            },
            "by_review_score": {
                "description": "Top 10 sellers by review score (min 10 orders)",
                "data": []
            }
        },
        
        "bottom_performers": {
            "description": "Bottom 10 sellers by review score (min 10 orders)",
            "data": []
        },
        
        "concentration_analysis": {
            "description": "Revenue concentration metrics across sellers",
            "sellers_for_80pct_revenue": int(sellers_for_80pct),
            "top_10_revenue_share_pct": round(float(top_10_revenue_share), 2),
            "concentration_ratio_pct": round(float(sellers_for_80pct/total_sellers*100), 2)
        },
        
        "review_score_distribution": {
            "description": "Distribution of sellers by average review score (sellers with reviews only)",
            "data": []
        }
    }
    
    # Populate top performers by revenue
    top_by_revenue_reset = top_by_revenue.reset_index(drop=True)
    for _, row in top_by_revenue_reset.iterrows():
        output['top_performers']['by_revenue']['data'].append({
            "seller_id": str(row['seller_id']),
            "total_revenue": round(float(row['total_revenue']), 2),
            "revenue_percentage": float(row['revenue_pct']),
            "total_orders": int(row['total_orders']),
            "avg_review_score": round(float(row['avg_review_score']), 2) if pd.notna(row['avg_review_score']) else None,
            "avg_delivery_days": round(float(row['avg_delivery_days']), 1)
        })
    
    # Populate top performers by review score
    if len(df_min_orders) > 0:
        top_by_review_reset = top_by_review.reset_index(drop=True)
        for _, row in top_by_review_reset.iterrows():
            output['top_performers']['by_review_score']['data'].append({
                "seller_id": str(row['seller_id']),
                "avg_review_score": round(float(row['avg_review_score']), 2),
                "total_orders": int(row['total_orders']),
                "total_revenue": round(float(row['total_revenue']), 2),
                "avg_delivery_days": round(float(row['avg_delivery_days']), 1)
            })
        
        # Populate bottom performers by review score
        bottom_by_review_reset = bottom_by_review.reset_index(drop=True)
        for _, row in bottom_by_review_reset.iterrows():
            output['bottom_performers']['data'].append({
                "seller_id": str(row['seller_id']),
                "avg_review_score": round(float(row['avg_review_score']), 2),
                "total_orders": int(row['total_orders']),
                "total_revenue": round(float(row['total_revenue']), 2),
                "avg_delivery_days": round(float(row['avg_delivery_days']), 1)
            })
    
    # Populate review score distribution
    if len(df_with_reviews) > 0:
        review_dist = df_with_reviews['review_bracket'].value_counts().sort_index()
        for bracket in review_labels:
            count = int(review_dist.get(bracket, 0))
            pct = (count / len(df_with_reviews) * 100) if len(df_with_reviews) > 0 else 0
            output['review_score_distribution']['data'].append({
                "bracket": bracket,
                "seller_count": count,
                "percentage": round(float(pct), 1)
            })
    
    # Save to file if path is provided
    if path:
        path_obj = Path(path)
        path_obj.parent.mkdir(parents=True, exist_ok=True)
        with open(path_obj, 'w') as f:
            json.dump(output, f, indent=2, default=str)
        print(f"\nSeller performance analysis saved to: {path}")
    
    return output


# Seller Performance Data 
df5 = fetch_data_from_bq(q.GET_BI_SELLER_PERFORMANCE)
create_seller_performance_report(df=df5, path= directory / "seller_performance_report.json")

###################################################################################################################
#### Delivery Performance 
###################################################################################################################

def create_delivery_performance_report(df, path = None):
    """
    Analyze delivery performance and create a comprehensive report.
    Parameters:
    -----------
    df : Delivery performance dataframe with columns:
        - order_id, seller_id, actual_delivery_days, fulfillment_days, delay_vs_estimate, on_time_flag
    path : If provided, saves JSON to this path.
    """
    
    print("="*80)
    print("                *** Delivery Performance Analysis Report ***")
    print("="*80)
    
    # Data type conversions
    df[['actual_delivery_days', 'delay_vs_estimate', 'fulfillment_days']] = df[['actual_delivery_days', 'delay_vs_estimate', 'fulfillment_days']].astype(int)
    df['on_time_flag'] = df['on_time_flag'].astype(bool)

    # --- Overall Summary ---
    print("\n### Overall Summary ###")
    total_orders = len(df)
    total_on_time = int(df['on_time_flag'].sum())
    on_time_rate = (total_on_time / total_orders * 100) if total_orders > 0 else 0
    
    avg_actual_delivery = float(df['actual_delivery_days'].mean())
    avg_fulfillment = float(df['fulfillment_days'].mean())
    avg_delay = float(df['delay_vs_estimate'].mean())
    
    print(f"Total Orders: {total_orders:,}")
    print(f"On-Time Deliveries: {total_on_time:,} ({on_time_rate:.2f}%)")
    print(f"Late Deliveries: {total_orders - total_on_time:,} ({100 - on_time_rate:.2f}%)")
    print(f"Average Actual Delivery Days: {avg_actual_delivery:.2f}")
    print(f"Average Fulfillment Days: {avg_fulfillment:.2f}")
    print(f"Average Delay vs Estimate: {avg_delay:.2f} days")
    print("-" * 80)
    
    # --- Delivery Time Distribution ---
    print("\n### Delivery Time Distribution ###")
    delivery_bins = [0, 7, 14, 21, 30, float('inf')]
    delivery_labels = ['0-7 days', '8-14 days', '15-21 days', '22-30 days', '30+ days']
    df['delivery_bracket'] = pd.cut(df['actual_delivery_days'], bins=delivery_bins, labels=delivery_labels, right=True)
    
    delivery_dist = df['delivery_bracket'].value_counts().sort_index()
    for bracket in delivery_labels:
        count = delivery_dist.get(bracket, 0)
        pct = (count / total_orders * 100) if total_orders > 0 else 0
        print(f"{bracket:15s}: {count:7,} orders ({pct:5.2f}%)")
    print("-" * 80)
    
    # --- Delay Analysis ---
    print("\n### Delay Analysis ###")
    late_orders = df[~df['on_time_flag']].copy()
    if len(late_orders) > 0:
        avg_late_delay = float(late_orders['delay_vs_estimate'].mean())
        max_delay = int(late_orders['delay_vs_estimate'].max())
        min_delay = int(late_orders['delay_vs_estimate'].min())
        
        print(f"Late Orders: {len(late_orders):,}")
        print(f"Average Delay (late orders only): {avg_late_delay:.2f} days")
        print(f"Maximum Delay: {max_delay} days")
        print(f"Minimum Delay: {min_delay} days")
        
        # Delay severity distribution
        delay_bins = [1, 3, 7, 14, float('inf')]
        delay_labels = ['1-3 days late', '4-7 days late', '8-14 days late', '14+ days late']
        late_orders['delay_bracket'] = pd.cut(late_orders['delay_vs_estimate'], bins=delay_bins, labels=delay_labels, right=True)
        
        print("\nDelay Severity Distribution:")
        delay_dist = late_orders['delay_bracket'].value_counts().sort_index()
        for bracket in delay_labels:
            count = delay_dist.get(bracket, 0)
            pct = (count / len(late_orders) * 100) if len(late_orders) > 0 else 0
            print(f"  {bracket:20s}: {count:6,} orders ({pct:5.2f}%)")
    else:
        print("No late orders found!")
    print("-" * 80)
    
    # --- Top 10 Sellers by On-Time Performance ---
    print("\n### Top 10 Sellers by On-Time Performance (min 10 orders) ###")
    seller_stats = df.groupby('seller_id').agg({
        'order_id': 'count',
        'on_time_flag': 'sum',
        'actual_delivery_days': 'mean',
        'delay_vs_estimate': 'mean'
    }).reset_index()
    seller_stats.columns = ['seller_id', 'total_orders', 'on_time_orders', 'avg_delivery_days', 'avg_delay']
    
    # Filter sellers with at least 10 orders
    seller_stats_filtered = seller_stats[seller_stats['total_orders'] >= 10].copy()
    
    if len(seller_stats_filtered) > 0:
        seller_stats_filtered['on_time_rate'] = (seller_stats_filtered['on_time_orders'] / seller_stats_filtered['total_orders'] * 100).round(2)
        top_sellers = seller_stats_filtered.nlargest(10, 'on_time_rate').copy()
        top_sellers_display = top_sellers[['seller_id', 'total_orders', 'on_time_orders', 'on_time_rate', 'avg_delivery_days', 'avg_delay']].copy()
        top_sellers_display['on_time_rate'] = top_sellers_display['on_time_rate'].apply(lambda x: f"{x}%")
        top_sellers_display['avg_delivery_days'] = top_sellers_display['avg_delivery_days'].apply(lambda x: f"{x:.2f}")
        top_sellers_display['avg_delay'] = top_sellers_display['avg_delay'].apply(lambda x: f"{x:.2f}")
        top_sellers_display.columns = ['Seller ID', 'Total Orders', 'On-Time', 'On-Time Rate', 'Avg Delivery', 'Avg Delay']
        print(top_sellers_display.to_string(index=False))
    else:
        print("No sellers with >= 10 orders found")
    print("-" * 80)
    
    # --- Bottom 10 Sellers by On-Time Performance ---
    print("\n### Bottom 10 Sellers by On-Time Performance (min 10 orders) ###")
    if len(seller_stats_filtered) > 0:
        bottom_sellers = seller_stats_filtered.nsmallest(10, 'on_time_rate').copy()
        bottom_sellers_display = bottom_sellers[['seller_id', 'total_orders', 'on_time_orders', 'on_time_rate', 'avg_delivery_days', 'avg_delay']].copy()
        bottom_sellers_display['on_time_rate'] = bottom_sellers_display['on_time_rate'].apply(lambda x: f"{x}%")
        bottom_sellers_display['avg_delivery_days'] = bottom_sellers_display['avg_delivery_days'].apply(lambda x: f"{x:.2f}")
        bottom_sellers_display['avg_delay'] = bottom_sellers_display['avg_delay'].apply(lambda x: f"{x:.2f}")
        bottom_sellers_display.columns = ['Seller ID', 'Total Orders', 'On-Time', 'On-Time Rate', 'Avg Delivery', 'Avg Delay']
        print(bottom_sellers_display.to_string(index=False))
    else:
        print("No sellers with >= 10 orders found")
    print("-" * 80)
    
    # --- Fulfillment Speed Analysis ---
    print("\n### Fulfillment Speed Analysis ###")
    fulfillment_bins = [0, 1, 3, 7, float('inf')]
    fulfillment_labels = ['Same day', '2-3 days', '4-7 days', '7+ days']
    df['fulfillment_bracket'] = pd.cut(df['fulfillment_days'], bins=fulfillment_bins, labels=fulfillment_labels, right=True)
    
    fulfillment_dist = df['fulfillment_bracket'].value_counts().sort_index()
    for bracket in fulfillment_labels:
        count = fulfillment_dist.get(bracket, 0)
        pct = (count / total_orders * 100) if total_orders > 0 else 0
        print(f"{bracket:15s}: {count:7,} orders ({pct:5.2f}%)")
    print("-" * 80)
    
    print("\n" + "="*80)
    
    # --- Build JSON Output ---
    output = {
        "description": "Delivery performance analysis including on-time rates, delays, and seller performance",
        
        "summary": {
            "total_orders": int(total_orders),
            "on_time_deliveries": int(total_on_time),
            "on_time_rate_pct": round(float(on_time_rate), 2),
            "late_deliveries": int(total_orders - total_on_time),
            "late_rate_pct": round(float(100 - on_time_rate), 2),
            "avg_actual_delivery_days": round(float(avg_actual_delivery), 2),
            "avg_fulfillment_days": round(float(avg_fulfillment), 2),
            "avg_delay_vs_estimate": round(float(avg_delay), 2)
        },
        
        "delivery_time_distribution": {
            "description": "Distribution of orders by actual delivery time brackets",
            "data": []
        },
        
        "delay_analysis": {
            "description": "Analysis of late deliveries and delay patterns",
            "late_orders_count": int(len(late_orders)),
            "avg_delay_late_orders": round(float(avg_late_delay), 2) if len(late_orders) > 0 else 0,
            "max_delay": int(max_delay) if len(late_orders) > 0 else 0,
            "min_delay": int(min_delay) if len(late_orders) > 0 else 0,
            "delay_severity_distribution": []
        },
        
        "seller_performance": {
            "top_10_sellers": {
                "description": "Top 10 sellers by on-time rate (min 10 orders)",
                "data": []
            },
            "bottom_10_sellers": {
                "description": "Bottom 10 sellers by on-time rate (min 10 orders)",
                "data": []
            }
        },
        
        "fulfillment_speed_distribution": {
            "description": "Distribution of orders by fulfillment time (order to shipment).",
            "data": []
        }
    }
    
    # Populate delivery time distribution
    for bracket in delivery_labels:
        count = int(delivery_dist.get(bracket, 0))
        pct = (count / total_orders * 100) if total_orders > 0 else 0
        output['delivery_time_distribution']['data'].append({
            "bracket": bracket,
            "order_count": count,
            "percentage": round(float(pct), 2)
        })
    
    # Populate delay severity distribution
    if len(late_orders) > 0:
        delay_dist = late_orders['delay_bracket'].value_counts().sort_index()
        for bracket in delay_labels:
            count = int(delay_dist.get(bracket, 0))
            pct = (count / len(late_orders) * 100) if len(late_orders) > 0 else 0
            output['delay_analysis']['delay_severity_distribution'].append({
                "bracket": bracket,
                "order_count": count,
                "percentage": round(float(pct), 2)
            })
    
    # Populate top sellers
    if len(seller_stats_filtered) > 0:
        top_sellers_reset = top_sellers.reset_index(drop=True)
        for _, row in top_sellers_reset.iterrows():
            output['seller_performance']['top_10_sellers']['data'].append({
                "seller_id": str(row['seller_id']),
                "total_orders": int(row['total_orders']),
                "on_time_orders": int(row['on_time_orders']),
                "on_time_rate_pct": float(row['on_time_rate']),
                "avg_delivery_days": round(float(row['avg_delivery_days']), 2),
                "avg_delay": round(float(row['avg_delay']), 2)
            })
        
        # Populate bottom sellers
        bottom_sellers_reset = bottom_sellers.reset_index(drop=True)
        for _, row in bottom_sellers_reset.iterrows():
            output['seller_performance']['bottom_10_sellers']['data'].append({
                "seller_id": str(row['seller_id']),
                "total_orders": int(row['total_orders']),
                "on_time_orders": int(row['on_time_orders']),
                "on_time_rate_pct": float(row['on_time_rate']),
                "avg_delivery_days": round(float(row['avg_delivery_days']), 2),
                "avg_delay": round(float(row['avg_delay']), 2)
            })
    
    # Populate fulfillment speed distribution
    fulfillment_dist = df['fulfillment_bracket'].value_counts().sort_index()
    for bracket in fulfillment_labels:
        count = int(fulfillment_dist.get(bracket, 0))
        pct = (count / total_orders * 100) if total_orders > 0 else 0
        output['fulfillment_speed_distribution']['data'].append({
            "bracket": bracket,
            "order_count": count,
            "percentage": round(float(pct), 2)
        })
    
    # Save to file if path is provided
    if path:
        path_obj = Path(path)
        path_obj.parent.mkdir(parents=True, exist_ok=True)
        with open(path_obj, 'w') as f:
            json.dump(output, f, indent=2, default=str)
        print(f"\nDelivery performance analysis saved to: {path}")
    return output

# Delivery Performance Data 
df6 = fetch_data_from_bq(q.GET_delivery_performance)
create_delivery_performance_report(df=df6, path= directory / "delivery_performance_report.json")


###################################################################################################################
#### Region / Province Performance 
###################################################################################################################

def create_region_performance_report(df, path=None):
    """
    Analyze regional performance and create a comprehensive report.
    Parameters:
    -----------
    df : Region performance dataframe with columns:
        - province, latitude, longitude, total_customers, 
          total_orders, total_spending
    path : If provided, saves JSON to this path.
    """
    
    print("="*80)
    print("                *** Regional Performance Analysis Report ***")
    print("="*80)
    
    # Calculate excluded data (province = None)
    excluded_data = df[df['province'].isna()].copy() if df['province'].isna().any() else None
    excluded_orders = int(excluded_data['total_orders'].sum()) if excluded_data is not None and len(excluded_data) > 0 else 0
    excluded_customers = int(excluded_data['total_customers'].sum()) if excluded_data is not None and len(excluded_data) > 0 else 0
    excluded_spending = float(excluded_data['total_spending'].sum()) if excluded_data is not None and len(excluded_data) > 0 else 0
    
    # Filter to only valid provinces for analysis
    df = df[df['province'].notna()].copy()
    
    # Data type conversions
    int_cols = ['total_customers', 'total_orders']
    flt_cols = ['latitude', 'longitude', 'total_spending']
    df[int_cols] = df[int_cols].astype(int)
    df[flt_cols] = df[flt_cols].astype(float)
    
    # Calculate additional metrics
    df['avg_spending_per_customer'] = df['total_spending'] / df['total_customers']
    df['avg_spending_per_order'] = df['total_spending'] / df['total_orders']

    # --- Overall Summary ---
    print("\n### Overall Summary ###")
    if excluded_orders > 0:
        print(f"Note: Excludes {excluded_orders:,} orders ({excluded_customers:,} customers, ${excluded_spending:,.2f}) without valid region information")
    total_provinces = len(df)
    total_customers = int(df['total_customers'].sum())
    total_orders = int(df['total_orders'].sum())
    total_spending = float(df['total_spending'].sum())
    avg_spending_per_customer = total_spending / total_customers if total_customers > 0 else 0
    avg_spending_per_order = total_spending / total_orders if total_orders > 0 else 0
    
    print(f"Total Provinces: {total_provinces:,}")
    print(f"Total Customers: {total_customers:,}")
    print(f"Total Orders: {total_orders:,}")
    print(f"Total Spending: ${total_spending:,.2f}")
    print(f"Avg Spending per Customer: ${avg_spending_per_customer:.2f}")
    print(f"Avg Spending per Order: ${avg_spending_per_order:.2f}")
    print("-" * 80)
    
    # --- Top 10 Provinces by Total Spending ---
    print("\n### Top 10 Provinces by Total Spending ###")
    top_by_spending = df.nlargest(10, 'total_spending').copy()
    
    # Calculate spending percentage
    top_by_spending['spending_pct'] = (top_by_spending['total_spending'] / total_spending * 100).round(2)
    
    top_spending_display = top_by_spending[['province', 'total_spending', 'spending_pct',
                                             'total_customers', 'total_orders', 
                                             'avg_spending_per_customer']].copy()
    top_spending_display['total_spending'] = top_spending_display['total_spending'].apply(lambda x: f"${x:,.2f}")
    top_spending_display['spending_pct'] = top_spending_display['spending_pct'].apply(lambda x: f"{x}%")
    top_spending_display['avg_spending_per_customer'] = top_spending_display['avg_spending_per_customer'].apply(lambda x: f"${x:.2f}")
    top_spending_display.columns = ['Province', 'Total Spending', 'Spending %', 'Customers', 'Orders', 'Avg per Customer']
    
    print(top_spending_display.to_string(index=False))
    print("-" * 80)
    
    # --- Top 10 Provinces by Customer Count ---
    print("\n### Top 10 Provinces by Customer Count ###")
    top_by_customers = df.nlargest(10, 'total_customers').copy()
    
    top_customers_display = top_by_customers[['province', 'total_customers', 'total_orders',
                                               'total_spending', 'avg_spending_per_customer']].copy()
    top_customers_display['total_spending'] = top_customers_display['total_spending'].apply(lambda x: f"${x:,.2f}")
    top_customers_display['avg_spending_per_customer'] = top_customers_display['avg_spending_per_customer'].apply(lambda x: f"${x:.2f}")
    top_customers_display.columns = ['Province', 'Customers', 'Orders', 'Total Spending', 'Avg per Customer']
    
    print(top_customers_display.to_string(index=False))
    print("-" * 80)
    
    # --- Top 10 Provinces by Avg Spending per Customer ---
    print("\n### Top 10 Provinces by Avg Spending per Customer (min 100 customers) ###")
    df_min_customers = df[df['total_customers'] >= 100].copy()
    
    if len(df_min_customers) > 0:
        top_by_avg_spending = df_min_customers.nlargest(10, 'avg_spending_per_customer').copy()
        
        top_avg_display = top_by_avg_spending[['province', 'avg_spending_per_customer',
                                                'total_customers', 'total_orders', 
                                                'total_spending']].copy()
        top_avg_display['avg_spending_per_customer'] = top_avg_display['avg_spending_per_customer'].apply(lambda x: f"${x:.2f}")
        top_avg_display['total_spending'] = top_avg_display['total_spending'].apply(lambda x: f"${x:,.2f}")
        top_avg_display.columns = ['Province', 'Avg per Customer', 'Customers', 'Orders', 'Total Spending']
        
        print(top_avg_display.to_string(index=False))
    else:
        print("No provinces with >= 100 customers found")
    print("-" * 80)
    
    # --- Bottom 10 Provinces by Total Spending ---
    print("\n### Bottom 10 Provinces by Total Spending ###")
    bottom_by_spending = df.nsmallest(10, 'total_spending').copy()
    
    bottom_spending_display = bottom_by_spending[['province', 'total_spending', 
                                                   'total_customers', 'total_orders']].copy()
    bottom_spending_display['total_spending'] = bottom_spending_display['total_spending'].apply(lambda x: f"${x:,.2f}")
    bottom_spending_display.columns = ['Province', 'Total Spending', 'Customers', 'Orders']
    
    print(bottom_spending_display.to_string(index=False))
    print("-" * 80)
    
    # --- Regional Concentration Analysis ---
    print("\n### Regional Concentration Analysis ###")
    df_sorted = df.sort_values('total_spending', ascending=False).copy()
    df_sorted['cumulative_spending_pct'] = (df_sorted['total_spending'].cumsum() / total_spending * 100)
    
    provinces_for_80pct = (df_sorted['cumulative_spending_pct'] <= 80).sum()
    top_5_spending_share = (df.nlargest(5, 'total_spending')['total_spending'].sum() / total_spending * 100)
    
    print(f"Top {provinces_for_80pct} provinces account for 80% of spending")
    print(f"  → Concentration ratio: {provinces_for_80pct}/{total_provinces} = {(provinces_for_80pct/total_provinces*100):.1f}%")
    print(f"Top 5 provinces account for {top_5_spending_share:.1f}% of total spending")
    print("-" * 80)
    
    print("\n" + "="*80)
    
    # --- Build JSON Output ---
    output = {
        "description": "Regional performance analysis including spending, customers, and concentration metrics",
        
        "data_quality": {
            "excluded_orders": int(excluded_orders),
            "excluded_customers": int(excluded_customers),
            "excluded_spending": round(float(excluded_spending), 2),
            "note": "Orders without valid region information (province = None)"
        },
        
        "summary": {
            "total_provinces": int(total_provinces),
            "total_customers": int(total_customers),
            "total_orders": int(total_orders),
            "total_spending": round(float(total_spending), 2),
            "avg_spending_per_customer": round(float(avg_spending_per_customer), 2),
            "avg_spending_per_order": round(float(avg_spending_per_order), 2)
        },
        
        "top_performers": {
            "by_total_spending": {
                "description": "Top 10 provinces by total spending",
                "data": []
            },
            "by_customer_count": {
                "description": "Top 10 provinces by customer count",
                "data": []
            },
            "by_avg_spending_per_customer": {
                "description": "Top 10 provinces by average spending per customer (min 100 customers)",
                "data": []
            }
        },
        
        "bottom_performers": {
            "description": "Bottom 10 provinces by total spending",
            "data": []
        },
        
        "concentration_analysis": {
            "description": "Spending concentration metrics across provinces",
            "provinces_for_80pct_spending": int(provinces_for_80pct),
            "top_5_spending_share_pct": round(float(top_5_spending_share), 2),
            "concentration_ratio_pct": round(float(provinces_for_80pct/total_provinces*100), 2)
        }
    }
    
    # Populate top performers by total spending
    top_by_spending_reset = top_by_spending.reset_index(drop=True)
    for _, row in top_by_spending_reset.iterrows():
        output['top_performers']['by_total_spending']['data'].append({
            "province": str(row['province']),
            "latitude": round(float(row['latitude']), 4),
            "longitude": round(float(row['longitude']), 4),
            "total_spending": round(float(row['total_spending']), 2),
            "spending_percentage": float(row['spending_pct']),
            "total_customers": int(row['total_customers']),
            "total_orders": int(row['total_orders']),
            "avg_spending_per_customer": round(float(row['avg_spending_per_customer']), 2)
        })
    
    # Populate top performers by customer count
    top_by_customers_reset = top_by_customers.reset_index(drop=True)
    for _, row in top_by_customers_reset.iterrows():
        output['top_performers']['by_customer_count']['data'].append({
            "province": str(row['province']),
            "latitude": round(float(row['latitude']), 4),
            "longitude": round(float(row['longitude']), 4),
            "total_customers": int(row['total_customers']),
            "total_orders": int(row['total_orders']),
            "total_spending": round(float(row['total_spending']), 2),
            "avg_spending_per_customer": round(float(row['avg_spending_per_customer']), 2)
        })
    
    # Populate top performers by avg spending per customer
    if len(df_min_customers) > 0:
        top_by_avg_spending_reset = top_by_avg_spending.reset_index(drop=True)
        for _, row in top_by_avg_spending_reset.iterrows():
            output['top_performers']['by_avg_spending_per_customer']['data'].append({
                "province": str(row['province']),
                "latitude": round(float(row['latitude']), 4),
                "longitude": round(float(row['longitude']), 4),
                "avg_spending_per_customer": round(float(row['avg_spending_per_customer']), 2),
                "total_customers": int(row['total_customers']),
                "total_orders": int(row['total_orders']),
                "total_spending": round(float(row['total_spending']), 2)
            })
    
    # Populate bottom performers
    bottom_by_spending_reset = bottom_by_spending.reset_index(drop=True)
    for _, row in bottom_by_spending_reset.iterrows():
        output['bottom_performers']['data'].append({
            "province": str(row['province']),
            "latitude": round(float(row['latitude']), 4),
            "longitude": round(float(row['longitude']), 4),
            "total_spending": round(float(row['total_spending']), 2),
            "total_customers": int(row['total_customers']),
            "total_orders": int(row['total_orders'])
        })
    
    # Save to file if path is provided
    if path:
        path_obj = Path(path)
        path_obj.parent.mkdir(parents=True, exist_ok=True)
        with open(path_obj, 'w') as f:
            json.dump(output, f, indent=2, default=str)
        print(f"\nRegional performance analysis saved to: {path}")
    return output

# Region Performance Data 
df7 = fetch_data_from_bq(q.GET_region_performance)
create_region_performance_report(df=df7, path= directory / "region_performance_report.json")


###################################################################################################################
#### Overal Business Summary / Main KPIs  + Monthly Time Series & MoM
###################################################################################################################

def create_overall_business_metrics_report(df, path=None):
    """
    Create overall business metrics report.
    Parameters:
    -----------
    df : Business metrics dataframe with columns:
        - total_orders, total_customers, total_sellers, total_items_ordered,
          total_revenue, avg_order_value, avg_basket_size
    path : If provided, saves JSON to this path.
    """
    
    print("="*80)
    print("                 *** Overall Business Metrics Report ***")
    print("="*80)
    
    # Get the single row of data
    row = df.iloc[0]
    
    # Data type conversions
    total_orders = int(row['total_orders'])
    total_customers = int(row['total_customers'])
    total_sellers = int(row['total_sellers'])
    total_items = int(row['total_items_ordered'])
    total_revenue = float(row['total_revenue'])
    avg_order_value = float(row['avg_order_value'])
    avg_basket_size = float(row['avg_basket_size'])
    
    # --- Overall Summary ---
    print("\n### Overall Business Metrics ###")
    print(f"Total Orders: {total_orders:,}")
    print(f"Total Customers: {total_customers:,}")
    print(f"Total Sellers: {total_sellers:,}")
    print(f"Total Items Ordered: {total_items:,}")
    print(f"Total Revenue: ${total_revenue:,.2f}")
    print("-" * 80)
    
    # --- Key Performance Indicators ---
    print("\n### Key Performance Indicators ###")
    print(f"Average Order Value (AOV): ${avg_order_value:.2f}")
    print(f"Average Basket Size: {avg_basket_size:.2f} items per order")
    print(f"Revenue per Customer: ${(total_revenue/total_customers):.2f}")
    print(f"Orders per Customer: {(total_orders/total_customers):.2f}")
    print(f"Revenue per Seller: ${(total_revenue/total_sellers):.2f}")
    print(f"Orders per Seller: {(total_orders/total_sellers):.2f}")
    print("-" * 80)
    
    print("\n" + "="*80)
    
    # --- Build JSON Output ---
    output = {
        "description": "Overall business metrics including orders, revenue, and key performance indicators",
        
        "business_metrics": {
            "total_orders": total_orders,
            "total_customers": total_customers,
            "total_sellers": total_sellers,
            "total_items_ordered": total_items,
            "total_revenue": round(total_revenue, 2)
        },
        
        "key_performance_indicators": {
            "avg_order_value": round(avg_order_value, 2),
            "avg_basket_size": round(avg_basket_size, 2),
            "revenue_per_customer": round(total_revenue / total_customers, 2),
            "orders_per_customer": round(total_orders / total_customers, 2),
            "revenue_per_seller": round(total_revenue / total_sellers, 2),
            "orders_per_seller": round(total_orders / total_sellers, 2)
        }
    }
    
    # Save to file if path is provided
    if path:
        path_obj = Path(path)
        path_obj.parent.mkdir(parents=True, exist_ok=True)
        with open(path_obj, 'w') as f:
            json.dump(output, f, indent=2, default=str)
        print(f"\nOverall business metrics saved to: {path}")
    
    return output


def create_monthly_time_series_report(df, path=None):
    """
    Create monthly business metrics report - simple time series with MoM growth.
    Parameters:
    -----------
    df : Monthly business metrics dataframe with columns:
        - month, total_orders, total_customers, total_sellers, total_items_ordered,
          total_revenue, avg_order_value, avg_basket_size
    path : If provided, saves JSON to this path.
    """
    
    print("="*80)
    print("                *** Monthly Business Metrics Report ***")
    print("="*80)
    
    # Data type conversions
    df['month'] = pd.to_datetime(df['month'])
    int_cols = ['total_orders', 'total_customers', 'total_sellers', 'total_items_ordered']
    flt_cols = ['total_revenue', 'avg_order_value', 'avg_basket_size']
    df[int_cols] = df[int_cols].astype(int)
    df[flt_cols] = df[flt_cols].astype(float)
    
    # Sort by month
    df = df.sort_values('month').reset_index(drop=True)
    df['year'] = df['month'].dt.year
    
    # Calculate MoM changes
    df['revenue_mom_change'] = df['total_revenue'].diff()
    df['revenue_mom_pct'] = df['total_revenue'].pct_change() * 100
    df['orders_mom_change'] = df['total_orders'].diff()
    df['orders_mom_pct'] = df['total_orders'].pct_change() * 100
    df['customers_mom_change'] = df['total_customers'].diff()
    df['customers_mom_pct'] = df['total_customers'].pct_change() * 100
    
    # --- Overall Summary ---
    print("\n### Overall Summary ###")
    total_revenue = float(df['total_revenue'].sum())
    total_orders = int(df['total_orders'].sum())
    
    print(f"Period: {df['month'].min().strftime('%Y-%m')} to {df['month'].max().strftime('%Y-%m')}")
    print(f"Total Months: {len(df)}")
    print(f"Total Revenue: ${total_revenue:,.2f}")
    print(f"Total Orders: {total_orders:,}")
    print(f"Avg Monthly Revenue: ${(total_revenue/len(df)):,.2f}")
    print(f"Avg Monthly Orders: {(total_orders/len(df)):,.0f}")
    print("-" * 80)
    
    # --- Monthly Performance ---
    print("\n### Monthly Performance ###")
    display_monthly = df[['month', 'total_orders', 'total_customers', 'total_revenue', 
                          'avg_order_value', 'avg_basket_size']].copy()
    display_monthly['month'] = display_monthly['month'].dt.strftime('%Y-%m')
    display_monthly['total_revenue'] = display_monthly['total_revenue'].apply(lambda x: f"${x:,.2f}")
    display_monthly['avg_order_value'] = display_monthly['avg_order_value'].apply(lambda x: f"${x:.2f}")
    display_monthly['avg_basket_size'] = display_monthly['avg_basket_size'].apply(lambda x: f"{x:.2f}")
    display_monthly.columns = ['Month', 'Orders', 'Customers', 'Revenue', 'AOV', 'Basket Size']
    
    print(display_monthly.to_string(index=False))
    print("-" * 80)
    
    # --- Month-over-Month Growth ---
    print("\n### Month-over-Month Growth ###")
    growth_display = df[['month', 'total_orders', 'orders_mom_pct', 
                         'total_customers', 'customers_mom_pct',
                         'total_revenue', 'revenue_mom_pct']].copy()
    growth_display['month'] = growth_display['month'].dt.strftime('%Y-%m')
    growth_display['orders_mom_pct'] = growth_display['orders_mom_pct'].apply(
        lambda x: f"{x:+.1f}%" if pd.notna(x) else "N/A"
    )
    growth_display['customers_mom_pct'] = growth_display['customers_mom_pct'].apply(
        lambda x: f"{x:+.1f}%" if pd.notna(x) else "N/A"
    )
    growth_display['total_revenue'] = growth_display['total_revenue'].apply(lambda x: f"${x:,.2f}")
    growth_display['revenue_mom_pct'] = growth_display['revenue_mom_pct'].apply(
        lambda x: f"{x:+.1f}%" if pd.notna(x) else "N/A"
    )
    growth_display.columns = ['Month', 'Orders', 'MoM %', 'Customers', 'MoM %', 'Revenue', 'MoM %']
    
    print(growth_display.to_string(index=False))
    print("-" * 80)
    
    print("\n" + "="*80)
    
    # --- Build JSON Output ---
    output = {
        "description": "Monthly business metrics time series with month-over-month growth",
        
        "summary": {
            "period_start": df['month'].min().strftime('%Y-%m'),
            "period_end": df['month'].max().strftime('%Y-%m'),
            "total_months": int(len(df)),
            "total_revenue": round(total_revenue, 2),
            "total_orders": int(total_orders),
            "avg_monthly_revenue": round(total_revenue / len(df), 2),
            "avg_monthly_orders": round(total_orders / len(df), 0)
        },
        
        "monthly_data": []
    }
    
    # Populate monthly data
    for _, row in df.iterrows():
        output['monthly_data'].append({
            "month": row['month'].strftime('%Y-%m'),
            "year": int(row['year']),
            "total_orders": int(row['total_orders']),
            "total_customers": int(row['total_customers']),
            "total_sellers": int(row['total_sellers']),
            "total_items_ordered": int(row['total_items_ordered']),
            "total_revenue": round(float(row['total_revenue']), 2),
            "avg_order_value": round(float(row['avg_order_value']), 2),
            "avg_basket_size": round(float(row['avg_basket_size']), 2),
            "orders_mom_change": int(row['orders_mom_change']) if pd.notna(row['orders_mom_change']) else None,
            "orders_mom_pct": round(float(row['orders_mom_pct']), 2) if pd.notna(row['orders_mom_pct']) else None,
            "customers_mom_change": int(row['customers_mom_change']) if pd.notna(row['customers_mom_change']) else None,
            "customers_mom_pct": round(float(row['customers_mom_pct']), 2) if pd.notna(row['customers_mom_pct']) else None,
            "revenue_mom_change": round(float(row['revenue_mom_change']), 2) if pd.notna(row['revenue_mom_change']) else None,
            "revenue_mom_pct": round(float(row['revenue_mom_pct']), 2) if pd.notna(row['revenue_mom_pct']) else None
        })
    
    # Save to file if path is provided
    if path:
        path_obj = Path(path)
        path_obj.parent.mkdir(parents=True, exist_ok=True)
        with open(path_obj, 'w') as f:
            json.dump(output, f, indent=2, default=str)
        print(f"\nMonthly business metrics saved to: {path}")
    return output


# Data Import and Reporting for Main Business Metrics & MoM Data
 
df8 = fetch_data_from_bq(q.GET_overal_business_metrics)
create_overall_business_metrics_report(df=df8, path= directory / "overall_business_metrics_report.json")

df9 = fetch_data_from_bq(q.GET_monthly_time_series)
create_monthly_time_series_report(df=df9, path= directory / "monthly_time_series_report.json")