import numpy as np
import pandas as pd
from . import sql_queries as q
from .utils import fetch_data_from_bq
import json
from pathlib import Path
from typing import Optional, Dict, Any
from datetime import datetime


### Cohort Cohort Analysis Data to JSON Format


def create_cohort_report(df, path= None):
    """
    Converts a pre-calculated Cohort Analysis DataFrame into a comprehensive
    printed report and a structured JSON file.

    Parameters:
    df : Cohort analysis dataframe with pre-calculated cohort data.
    path : If provided, saves JSON output to this file path. If None, only returns dict.
    """

    # Separate DataFrames for Matrix and Averages
 
    matrix_df = df[df['is_weighted_average'] == False].copy()
    avg_df = df[df['is_weighted_average'] == True].copy()
    avg_df['retention_rate'] = (avg_df['retention_rate'] * 100).round(2) # retention rate converted to percentage

    # --- Define JSON Descriptions ---
    # Define these early so we can print them in the report header
    OVERALL_REPORT_DESCRIPTION = "Customer Cohort Analysis: retention rates (%) and total spending. Each cohort represents customers who made their first purchase in a specific month."
    AVERAGE_BY_PERIOD_INDEX_DESCRIPTION = (
        "Cross-cohort aggregations by period index. The 'period_index' represents months elapsed since that cohort's start. "
        "This metric summarizes the overall health and retention of the entire customer base based on their age (e.g., all 3-month-old customers). "
        "Retention rates are expressed in percentages."
    )
    
    print("="*80)
    print("                      *** Customer Cohort Analysis Report ***")
    print("Note that Retention rates are in percentage and total spending are in USD.")
    print("="*80)

    # Overall Summary 
    print("\n### Overall Summary ###")
    # Total distinct cohorts created during the analysis period.
    total_cohorts = matrix_df['cohort_period'].nunique()
    # Total unique customers who made a first purchase (initial cohort size).
    total_customers = int(matrix_df.groupby('cohort_period')['customers_in_cohort'].max().sum())
    # Total revenue generated by all orders within the scope of this cohort analysis.
    total_revenue = float(matrix_df['total_spent'].sum())

    analysis_start = pd.to_datetime(matrix_df['cohort_period'].min()).strftime('%Y-%m')
    analysis_end = pd.to_datetime(matrix_df['order_period'].max()).strftime('%Y-%m')

    print(f"Total Cohorts: {total_cohorts}")
    print(f"Total Customers: {total_customers:,}")
    print(f"Total Revenue: ${total_revenue:,.2f}")
    print(f"Analysis Period: {analysis_start} to {analysis_end}")
    print("-" * 80)

    # Build overall summary JSON block
    overall_summary = {
        "total_cohorts": total_cohorts,
        "total_customers": total_customers,
        "total_revenue": round(total_revenue, 2),
        "analysis_period_start": analysis_start,
        "analysis_period_end": analysis_end
    }

    # Cross-Cohort Aggregations (by Period Index) 
    print("\n### Cross-Cohort Aggregation Results (by Period Index) ###")
    print("Cross-cohort aggregations by period index (months elapsed since that cohort's start).")
    print("-" * 80)

    # Select pre-calculated data from the aggregated DataFrame
    avg_display = avg_df[['period_index', 'active_customers', 'retention_rate', 'total_spent']].copy()
    avg_display_table = avg_display.copy()
    avg_display_table.columns = ['Period Index', 'Active Customers (Total)', 'Retention % (Cross-Cohort)',
                                 'Total Spent (Aggregated)']

    avg_display_table['Retention % (Cross-Cohort)'] = avg_display_table['Retention % (Cross-Cohort)'].apply(
        lambda x: f"{x}%" if pd.notna(x) else "N/A"
    )
    avg_display_table['Total Spent (Aggregated)'] = avg_display_table['Total Spent (Aggregated)'].apply(
        lambda x: f"${x:,.2f}" if pd.notna(x) else "N/A"
    )

    print(avg_display_table.to_string(index=False))
    print("-" * 80)

    # Build JSON block for cross-cohort aggregations
    aggregated_by_index_month = []
    for _, row in avg_df.iterrows():
        aggregated_by_index_month.append({
            "period_index": int(row['period_index']) if pd.notna(row['period_index']) else None,
            "retention_rate": round(row['retention_rate'] * 100, 2) if pd.notna(row['retention_rate']) else None,
            "total_spent": round(row['total_spent'], 2) if pd.notna(row['total_spent']) else None,
            "total_active_customers": int(row['active_customers']) if pd.notna(row['active_customers']) else None
        })

    # Final Output Construction 
    output = {
        "description": OVERALL_REPORT_DESCRIPTION,
        "overall_summary": overall_summary,
        "average_by_period_index": {
            "description": AVERAGE_BY_PERIOD_INDEX_DESCRIPTION,
            "data": aggregated_by_index_month}
    }
    # Save and Return 
    if path:
        path_obj = Path(path)
        path_obj.parent.mkdir(parents=True, exist_ok=True)
        with open(path_obj, 'w') as f:
            json.dump(output, f, indent=2, default=str)
        print(f"\n Cohort analysis saved to: {path}")

    return output


### RFM Analysis Data to JSON Format

def create_rfm_report(df: pd.DataFrame, path: Optional[str] = None, further_notes="") -> Dict[str, Any]:
    """
    Convert RFM analysis DataFrame to JSON format with printed report. Additional notes can be provided.
    Parameters:
    -----------
    df : RFM dataframe with columns: customer_unique_id, total_orders, total_spent,
        recency_days, r_score, f_score, m_score, rfm_score, rfm_label, rfm_segment
    path : If provided, saves JSON to this path.
    Returns: Structured JSON-ready dictionary
    """
    
    # Convert data types
    int_columns = ['total_orders', 'recency_days', 'r_score', 'f_score', 'm_score',
                   'rfm_score', 'rfm_label']
    df[int_columns] = df[int_columns].astype(int)
    df['total_spent'] = df['total_spent'].astype(float)
    
    print("="*80)
    print("              *** RFM (Recency, Frequency, Monetary) Analysis Report ***")
    print("="*80)
    
    # --- Summary Statistics ---
    print("\n### Overall Summary ###")
    total_customers = len(df)
    total_revenue = float(df['total_spent'].sum())
    avg_customer_value = float(df['total_spent'].mean())
    avg_orders_per_customer = float(df['total_orders'].mean())
    avg_recency_days = float(df['recency_days'].mean())
    
    print(f"Total Customers: {total_customers:,}")
    print(f"Total Revenue: ${total_revenue:,.2f}")
    print(f"Average Customer Value: ${avg_customer_value:,.2f}")
    print(f"Average Orders per Customer: {avg_orders_per_customer:.2f}")
    print(f"Average Recency (Days): {avg_recency_days:.2f}")
    print("-" * 80)
    
    # --- RFM Score Distribution ---
    print("\n### RFM Score Distribution ###")
    r_avg = float(df['r_score'].mean())
    r_median = int(df['r_score'].median())
    f_avg = float(df['f_score'].mean())
    f_median = int(df['f_score'].median())
    m_avg = float(df['m_score'].mean())
    m_median = int(df['m_score'].median())
    
    rfm_stats = pd.DataFrame({
        'Score Type': ['Recency', 'Frequency', 'Monetary'],
        'Avg Score': [round(r_avg, 2), round(f_avg, 2), round(m_avg, 2)],
        'Median Score': [r_median, f_median, m_median],
        'Metric Avg': [
            f"{avg_recency_days:.2f} days",
            f"{avg_orders_per_customer:.2f} orders",
            f"${avg_customer_value:,.2f}"
        ]
    })
    print(rfm_stats.to_string(index=False))
    print("-" * 80)
    
    # --- Segment Distribution ---
    print("\n### Customer Segment Distribution ###")
    segment_dist = df.groupby('rfm_segment').agg({
        'customer_unique_id': 'count',
        'total_spent': 'sum',
        'total_orders': 'sum'
    }).reset_index()
    
    segment_dist['percentage'] = (segment_dist['customer_unique_id'] / total_customers * 100).round(2)
    segment_dist['revenue_percentage'] = (segment_dist['total_spent'] / total_revenue * 100).round(2)
    segment_dist = segment_dist.sort_values('total_spent', ascending=False)
    
    segment_display = segment_dist.copy()
    segment_display.columns = ['Segment', 'Customers', 'Total Revenue', 'Total Orders', 
                                'Customer %', 'Revenue %']
    segment_display['Total Revenue'] = segment_display['Total Revenue'].apply(lambda x: f"${x:,.2f}")
    segment_display['Customer %'] = segment_display['Customer %'].apply(lambda x: f"{x}%")
    segment_display['Revenue %'] = segment_display['Revenue %'].apply(lambda x: f"{x}%")
    
    print(segment_display.to_string(index=False))
    print("-" * 80)
    
    # --- Detailed Segment Metrics ---
    print("\n### Detailed Segment Metrics ###")
    segment_metrics = df.groupby('rfm_segment').agg({
        'total_orders': ['mean', 'median'],
        'total_spent': ['mean', 'median'],
        'recency_days': ['mean', 'median'],
        'r_score': 'mean',
        'f_score': 'mean',
        'm_score': 'mean'
    }).reset_index()
    
    segment_metrics.columns = ['segment', 'avg_orders', 'median_orders', 'avg_spent', 
                                'median_spent', 'avg_recency', 'median_recency',
                                'avg_r_score', 'avg_f_score', 'avg_m_score']
    
    segment_metrics_display = segment_metrics.copy()
    segment_metrics_display['avg_spent'] = segment_metrics_display['avg_spent'].apply(lambda x: f"${x:,.2f}")
    segment_metrics_display['median_spent'] = segment_metrics_display['median_spent'].apply(lambda x: f"${x:,.2f}")
    segment_metrics_display = segment_metrics_display[['segment', 'avg_orders', 'avg_spent', 
                                                         'avg_recency', 'avg_r_score', 
                                                         'avg_f_score', 'avg_m_score']]
    segment_metrics_display.columns = ['Segment', 'Avg Orders', 'Avg Spent', 'Avg Recency', 
                                        'Avg R', 'Avg F', 'Avg M']
    
    print(segment_metrics_display.round(2).to_string(index=False))
    print("-" * 80)
    
    # --- Top Segments ---
    print("\n### Top 5 Segments by Revenue ###")
    top_revenue = segment_dist.nlargest(5, 'total_spent')[['rfm_segment', 'total_spent', 'revenue_percentage']]
    top_revenue_display = top_revenue.copy()
    top_revenue_display['total_spent'] = top_revenue_display['total_spent'].apply(lambda x: f"${x:,.2f}")
    top_revenue_display['revenue_percentage'] = top_revenue_display['revenue_percentage'].apply(lambda x: f"{x}%")
    top_revenue_display.columns = ['Segment', 'Total Revenue', 'Revenue %']
    print(top_revenue_display.to_string(index=False))
    
    print("\n### Top 5 Segments by Customer Count ###")
    top_count = segment_dist.nlargest(5, 'customer_unique_id')[['rfm_segment', 'customer_unique_id', 'percentage']]
    top_count_display = top_count.copy()
    top_count_display['percentage'] = top_count_display['percentage'].apply(lambda x: f"{x}%")
    top_count_display.columns = ['Segment', 'Customer Count', 'Customer %']
    print(top_count_display.to_string(index=False))
    print(f"\n* Note that:\n {further_notes}")
    print("\n" + "="*80)
    
    # --- Build JSON Output ---
    output = {
        "description": "RFM (Recency, Frequency, Monetary) customer segmentation analysis",
    
        "summary": {
            "total_customers": int(total_customers),
            "total_revenue": round(total_revenue, 2),
            "avg_customer_value": round(avg_customer_value, 2),
            "avg_orders_per_customer": round(avg_orders_per_customer, 2),
            "avg_recency_days": round(avg_recency_days, 2)
        },
        
        "rfm_segment_distribution": {
            "description": "Customer count and value distribution across RFM segments",
            "data": []
        },
        
        "segment_metrics": {
            "description": "Detailed metrics for each customer segment",
            "data": []
        },
        
        "rfm_score_distribution": {
            "description": "Statistical distribution of R, F, and M scores",
            "recency": {
                "avg_score": round(r_avg, 2),
                "median_score": r_median,
                "avg_days": round(avg_recency_days, 2)
            },
            "frequency": {
                "avg_score": round(f_avg, 2),
                "median_score": f_median,
                "avg_orders": round(avg_orders_per_customer, 2)
            },
            "monetary": {
                "avg_score": round(m_avg, 2),
                "median_score": m_median,
                "avg_spent": round(avg_customer_value, 2)
            }
        },
        "Additional Note About Data": further_notes
    }
    
    # Populate segment distribution data (already sorted by revenue in descending order)
    for _, row in segment_dist.iterrows():
        output['rfm_segment_distribution']['data'].append({
            "segment": str(row['rfm_segment']),
            "customer_count": int(row['customer_unique_id']),
            "percentage_of_customers": float(row['percentage']),
            "total_revenue": round(float(row['total_spent']), 2),
            "percentage_of_revenue": float(row['revenue_percentage']),
            "total_orders": int(row['total_orders'])
        })
    
    # Populate segment metrics data
    for _, row in segment_metrics.iterrows():
        output['segment_metrics']['data'].append({
            "segment": str(row['segment']),
            "avg_orders": round(float(row['avg_orders']), 2),
            "median_orders": int(row['median_orders']),
            "avg_spent": round(float(row['avg_spent']), 2),
            "median_spent": round(float(row['median_spent']), 2),
            "avg_recency_days": round(float(row['avg_recency']), 2),
            "median_recency_days": int(row['median_recency']),
            "avg_rfm_scores": {
                "recency": round(float(row['avg_r_score']), 2),
                "frequency": round(float(row['avg_f_score']), 2),
                "monetary": round(float(row['avg_m_score']), 2)
            }
        })

    # Save to file if path is provided
    if path:
        path_obj = Path(path)
        path_obj.parent.mkdir(parents=True, exist_ok=True)
        with open(path_obj, 'w') as f:
            json.dump(output, f, indent=2, default=str)
        print(f"\nRFM analysis saved to: {path}")
    
    return output



# Performing analysis and generating reports

directory = Path(__file__).resolve().parents[2] / "python" / "outputs" / "Analysis" 

# Cohort Customer Retention Data
df1 = fetch_data_from_bq(q.GET_BI_CUSTOMER_COHORTS)
create_cohort_report(df=df1, path= directory / "cohort_analysis_report.json")

# RFM Analysis Data 
df2 = fetch_data_from_bq(q.GET_BI_CUSTOMER_RFM)
create_rfm_report(df=df2, path= directory / "rfm_analysis_report.json", 
                  further_notes="The majority of customers (i.e. more than 95 percent of customers) only had only 1 order so the histogram of F (Frequency) is highly skewed")

