olist:
  outputs:
    dev:
      # dataset: olist-ecommerce-2025
      schema: rawdata
      job_execution_timeout_seconds: 600
      job_retries: 1
      keyfile: D:/My_Projects/olist-ecommerce-1234321-925167414fbb.json
      location: EU
      method: service-account
      priority: interactive
      project: olist-ecommerce-1234321
      threads: 1
      type: bigquery
  target: dev
