olist:
  outputs:
    dev:
      dataset: olist-ecommerce-2025
      job_execution_timeout_seconds: 600
      job_retries: 1
      keyfile: D:/My_Projects/dbt_project_OLIST/olist/olist-ecommerce-2025-90493c1e49bc.json
      location: EU
      method: service-account
      priority: interactive
      project: olist-ecommerce-2025
      threads: 1
      type: bigquery
  target: dev
